server:
  port: 8112

spring:
  application:
    name: payment-status-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

eurosa:
  downstream:
    payment-execution-service: http://localhost:8111
