"""Product branding — user-facing names (package/CLI remain migrate_framework)."""

from __future__ import annotations

from pathlib import Path

PRODUCT_NAME = "MATE"
PRODUCT_TAGLINE = "Modernization & Architecture Transformation Engine"
REPORT_FOOTER = (
    f"_Generated by {PRODUCT_NAME}. "
    "This report summarizes evidence-backed analysis and proposed modernization steps; "
    "execution remains developer-guided with human approval gates._"
)

_LOGO_FILENAME = "context-atlas-logo.jpg"


def product_logo_path() -> Path | None:
    """Bundled logo for Streamlit sidebar, favicon, and reports."""
    path = Path(__file__).resolve().parent / "ui" / "assets" / _LOGO_FILENAME
    return path if path.is_file() else None
