"""Product branding — user-facing names (package/CLI remain migrate_framework)."""

PRODUCT_NAME = "Context Atlas"
PRODUCT_TAGLINE = "Evidence-led estate assessment"
REPORT_FOOTER = (
    f"_Generated by {PRODUCT_NAME}. "
    "This report summarizes evidence-backed analysis and proposed migration steps; "
    "execution remains developer-guided with human approval gates._"
)
