server:
  port: 8102

spring:
  application:
    name: customer-address-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

eurosa:
  downstream:
    customer-identity-service: http://localhost:8101
