"""Assisted playbook task execution with reviewable file proposals."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from migrate_framework.migration.diff_utils import unified_diff
from migrate_framework.models import MigrationProject, new_id


def _context_slug(context_name: str | None) -> str:
    if not context_name:
        return "bounded-context"
    slug = context_name.lower()
    slug = re.sub(r"^extract\s+", "", slug)
    slug = re.sub(r"[^a-z0-9]+", "-", slug).strip("-")
    return slug or "bounded-context"


def _phase_for_task(project: MigrationProject, task: dict[str, Any]) -> dict[str, Any]:
    phase_num = task.get("phase")
    for phase in project.metadata.get("plan") or []:
        if phase.get("phase") == phase_num:
            return phase
    return {}


def _base_dir(project: MigrationProject, task: dict[str, Any]) -> str:
    phase = _phase_for_task(project, task)
    slug = _context_slug(phase.get("name") or task.get("context"))
    return f"target-contexts/{slug}"


def _file_proposal(
    project: MigrationProject,
    relative_path: str,
    content: str,
    action: str = "create",
) -> dict[str, Any]:
    source_root = project.repo_root()
    full_path = source_root / relative_path
    before = None
    if full_path.exists() and action == "modify":
        before = full_path.read_text(encoding="utf-8")
        action = "modify" if before != content else "create"
    elif full_path.exists():
        before = full_path.read_text(encoding="utf-8")
        action = "modify"

    return {
        "path": relative_path.replace("\\", "/"),
        "action": "modify" if before is not None and action != "create" else "create",
        "content": content,
        "before": before,
        "diff": unified_diff(relative_path, before, content, action),
    }


def _guidance_only(task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    services = ", ".join(phase.get("services") or []) or "see migration plan"
    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": (
            f"**Manual task:** {task.get('task')}\n\n"
            f"- **Phase:** {phase.get('name', 'cross-cutting')}\n"
            f"- **Services in scope:** {services}\n"
            f"- **Owner:** {task.get('owner', 'team')}\n\n"
            "No automated patch is generated for this task type. "
            "Use Cursor with the `migration-playbook` skill and attach relevant OpenAPI/SQL evidence."
        ),
        "files": [],
    }


def _proposal_scaffold(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    context_name = phase.get("name") or task.get("context") or "Bounded Context"
    services = phase.get("services") or []

    readme = f"""# {context_name}

Scaffold generated by the migration framework (review before merge).

## Objective
{phase.get("objective", "Consolidate granular services into this bounded context.")}

## Source services
{chr(10).join(f"- `{service}`" for service in services)}

## Next steps
1. Define aggregate roots and module boundaries
2. Add application services and REST adapters
3. Wire anti-corruption layers to legacy APIs during strangler migration
"""

    openapi = f"""openapi: 3.0.3
info:
  title: {context_name} API
  version: 0.1.0-draft
  description: Unified API scaffold — extend during migration Phase {phase.get("phase", 1)}
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
"""

    files = [
        _file_proposal(project, f"{base}/README.md", readme),
        _file_proposal(project, f"{base}/openapi.yaml", openapi),
    ]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": (
            f"Proposed scaffold for **{context_name}** under `{base}/`. "
            "Review the diff, apply selected files, then flesh out domain logic manually."
        ),
        "files": files,
    }


def _proposal_acl(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    services = phase.get("services") or ["legacy-service"]
    legacy = services[0]
    legacy_class = "".join(part.capitalize() for part in legacy.replace("-service", "").split("-"))

    client = f"""package com.eurosa.bank.migration.acl;

/**
 * ACL client stub for legacy `{legacy}`.
 * Review and align with the actual OpenAPI contract before cutover.
 */
public interface Legacy{legacy_class}Client {{

    String fetchLegacyResource(String resourceId);
}}
"""

    adapter = f"""package com.eurosa.bank.migration.acl;

/**
 * Anti-corruption layer translating legacy `{legacy}` responses
 * into the target bounded-context model.
 */
public class {legacy_class}AntiCorruptionLayer {{

    private final Legacy{legacy_class}Client legacyClient;

    public {legacy_class}AntiCorruptionLayer(Legacy{legacy_class}Client legacyClient) {{
        this.legacyClient = legacyClient;
    }}

    public String toDomainModel(String resourceId) {{
        return legacyClient.fetchLegacyResource(resourceId);
    }}
}}
"""

    files = [
        _file_proposal(
            project,
            f"{base}/src/main/java/com/eurosa/bank/migration/acl/Legacy{legacy_class}Client.java",
            client,
        ),
        _file_proposal(
            project,
            f"{base}/src/main/java/com/eurosa/bank/migration/acl/{legacy_class}AntiCorruptionLayer.java",
            adapter,
        ),
    ]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": (
            "Proposed **anti-corruption layer** stubs. Legacy calls stay isolated here "
            "so domain code does not depend on granular service DTOs."
        ),
        "files": files,
    }


def _proposal_schema_migration(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    db_hint = (phase.get("services") or ["service"])[0].split("-")[0]
    sql = f"""-- Phase {phase.get("phase", 1)} schema migration draft for {phase.get("name", "context")}
-- REVIEW WITH DBA BEFORE APPLYING

-- UP
CREATE TABLE IF NOT EXISTS migration_checkpoint (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    phase INT NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Example: consolidate shared tables into context schema
-- ALTER TABLE customer_db.customers ADD COLUMN context_migrated BOOLEAN DEFAULT FALSE;

-- DOWN (rollback)
-- DROP TABLE IF EXISTS migration_checkpoint;
"""

    files = [_file_proposal(project, f"{base}/migrations/V1__phase{phase.get('phase', 1)}_draft.sql", sql)]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": (
            f"Draft SQL migration with rollback notes. Shared-database consolidation for "
            f"**{phase.get('name', 'context')}** must be validated against `{db_hint}_db` evidence."
        ),
        "files": files,
    }


def _proposal_contract_tests(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    services = phase.get("services") or []
    service_list = ", ".join(f'"{service}"' for service in services)

    test_java = f"""package com.eurosa.bank.migration.tests;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Contract test placeholder — wire to legacy OpenAPI specs for:
 * {service_list}
 */
class LegacyOpenApiContractTest {{

    @Test
    void legacyContractsArePinned() {{
        assertTrue(true, "Replace with OpenAPI contract assertions against legacy services");
    }}
}}
"""

    files = [
        _file_proposal(
            project,
            f"{base}/src/test/java/com/eurosa/bank/migration/tests/LegacyOpenApiContractTest.java",
            test_java,
        )
    ]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": "Contract test stub to pin legacy behavior before consolidation cutover.",
        "files": files,
    }


def _proposal_aggregate_roots(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    services = phase.get("services") or []
    doc = f"""# Aggregate roots — {phase.get("name", "Bounded Context")}

## Candidate aggregates (draft)
- **Customer** — identity, status (from {", ".join(services[:3])}{"..." if len(services) > 3 else ""})
- **CustomerProfile** — preferences, contact channels
- **CustomerAddress** — address book and validation rules

## Invariants to confirm with domain experts
1. Customer identity is the sole entry point for cross-aggregate references
2. Address changes do not mutate identity records directly
3. Status transitions are event-driven, not synchronous fan-out

## Evidence links
- Review shared tables in diagnosis `shared_database` smells
- Cross-check manifest services: {", ".join(services)}
"""

    files = [_file_proposal(project, f"{base}/docs/aggregate-roots.md", doc)]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": "Draft aggregate map for domain review — not applied to runtime code.",
        "files": files,
    }


def _proposal_unified_api(project: MigrationProject, task: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    base = _base_dir(project, task)
    context_name = phase.get("name") or "Bounded Context"
    paths = "\n".join(
        f"  /legacy/{service.replace('-service', '')}/{{id}}:\n"
        f"    get:\n"
        f"      summary: Strangler route to legacy {service}\n"
        f"      responses:\n"
        f"        '200':\n"
        f"          description: Proxied legacy response\n"
        for service in (phase.get("services") or [])[:5]
    )
    openapi = f"""openapi: 3.0.3
info:
  title: {context_name} Unified API (draft)
  version: 0.1.0-draft
paths:
{paths}
  /health:
    get:
      summary: Health
      responses:
        '200':
          description: OK
"""

    files = [_file_proposal(project, f"{base}/openapi.yaml", openapi, action="modify")]

    return {
        "proposal_id": new_id("proposal"),
        "task_id": task.get("id"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "guidance": "Unified API draft with strangler routes to legacy services. Review before publishing.",
        "files": files,
    }


def assist_playbook_task(project: MigrationProject, task: dict[str, Any]) -> dict[str, Any]:
    """Generate guidance and reviewable file proposals for a playbook task."""
    phase = _phase_for_task(project, task)
    text = (task.get("task") or "").lower()

    if "scaffold" in text:
        return _proposal_scaffold(project, task, phase)
    if "anti-corruption" in text or "anti corruption" in text:
        return _proposal_acl(project, task, phase)
    if "schema migration" in text or "migration script" in text:
        return _proposal_schema_migration(project, task, phase)
    if "contract test" in text:
        return _proposal_contract_tests(project, task, phase)
    if "aggregate root" in text:
        return _proposal_aggregate_roots(project, task, phase)
    if "unified api" in text:
        return _proposal_unified_api(project, task, phase)

    return _guidance_only(task, phase)


def get_playbook_tasks(project: MigrationProject) -> list[dict[str, Any]]:
    return list(project.metadata.get("playbook") or [])


def update_task_status(project: MigrationProject, task_id: str, status: str) -> None:
    for task in get_playbook_tasks(project):
        if task.get("id") == task_id:
            task["status"] = status
            break
    project.metadata["playbook"] = get_playbook_tasks(project)


def store_proposal(project: MigrationProject, proposal: dict[str, Any]) -> None:
    proposals = project.metadata.setdefault("playbook_proposals", {})
    proposals[proposal["task_id"]] = proposal


def get_proposal(project: MigrationProject, task_id: str) -> dict[str, Any] | None:
    return project.metadata.get("playbook_proposals", {}).get(task_id)


def apply_proposal_files(
    project: MigrationProject,
    proposal: dict[str, Any],
    selected_paths: set[str],
) -> list[str]:
    """Apply approved files from a proposal. Returns list of written paths."""
    source_root = project.repo_root()
    written: list[str] = []

    for file_entry in proposal.get("files") or []:
        path = file_entry.get("path", "")
        if path not in selected_paths:
            continue
        full_path = source_root / path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(file_entry.get("content", ""), encoding="utf-8")
        written.append(path)

    return written
